SELECT DEPARTMENT_ID, 
       DEPARTMENT_NAME, 
       GET_EMP_COUNT(DEPARTMENT_ID) CNT
FROM DEPARTMENTS;

SELECT DEPARTMENT_ID,
       DEPARTMENT_NAME,
       GET_TOTAL_ANNUAL_SALARY(DEPARTMENT_ID) DEPT_TOTAL_SALARY
FROM DEPARTMENTS;

