/*
    일정관리 관련 테이블
*/

CREATE TABLE COMM_TODO_CATEGORIES (
    CATEGORY_NO NUMBER(3),
    CATEGORY_NAME VARCHAR2(255) NOT NULL,
    
    CONSTRAINT CATNO_PK PRIMARY KEY (CATEGORY_NO)
);

CREATE TABLE COMM_TODOS (
    TODO_NO             NUMBER(6),
    CATEGORY_NO         NUMBER(3)       NOT NULL,
    TODO_TITLE          VARCHAR2(255)   NOT NULL,
    USER_NO             NUMBER(4)       NOT NULL,
    TODO_DATE           CHAR(10)        NOT NULL,
    TODO_CONTENT        VARCHAR2(2000)  NOT NULL,
    TODO_STATUS         VARCHAR2(255)   DEFAULT '처리예정',
    TODO_DELETED        CHAR(1)         DEFAULT 'N',
    TODO_UPDATED_DATE   DATE            DEFAULT SYSDATE,
    TODO_CREATED_DATE   DATE            DEFAULT SYSDATE,
    
    CONSTRAINT TODO_NO_PK PRIMARY KEY (TODO_NO),
    CONSTRAINT TODO_CATEGORYNO_FK FOREIGN KEY (CATEGORY_NO)
                                REFERENCES COMM_TODO_CATEGORIES (CATEGORY_NO),
    CONSTRAINT TODO_USERNO_FK FOREIGN KEY (USER_NO)
                              REFERENCES COMM_USERS (USER_NO),
    CONSTRAINT TODO_STATUS_CK CHECK (TODO_STATUS IN ('처리예정', '처리완료', '취소'))                             
);

CREATE SEQUENCE TODOS_SEQ START WITH 100000 NOCACHE;

INSERT INTO COMM_TODO_CATEGORIES VALUES(101, '회의');
INSERT INTO COMM_TODO_CATEGORIES VALUES(102, '출장');
INSERT INTO COMM_TODO_CATEGORIES VALUES(103, '휴가');
INSERT INTO COMM_TODO_CATEGORIES VALUES(104, '개발');
INSERT INTO COMM_TODO_CATEGORIES VALUES(105, '테스트');
INSERT INTO COMM_TODO_CATEGORIES VALUES(106, '배포');
INSERT INTO COMM_TODO_CATEGORIES VALUES(107, '교육');
INSERT INTO COMM_TODO_CATEGORIES VALUES(108, '외근');
INSERT INTO COMM_TODO_CATEGORIES VALUES(109, '외부회의');
INSERT INTO COMM_TODO_CATEGORIES VALUES(110, '기타');

COMMIT;