CREATE TABLE COMM_PRODUCT_CATEGORIES (
    CATEGORY_NO     NUMBER(4),
    CATEGORY_NAME   VARCHAR2(255) NOT NULL,
    CONSTRAINT PRODUCT_CATNO_PK PRIMARY KEY (CATEGORY_NO)
);

CREATE TABLE COMM_PRODUCT_COMPANIES (
    COMPANY_NO      NUMBER(4),
    COMPANY_NAME    VARCHAR2(255) NOT NULL,
    COMPANY_TEL     VARCHAR2(255) NOT NULL,
    COMPANY_CITY    VARCHAR2(255) NOT NULL,
    
    CONSTRAINT PRODUCT_COMPANYNO_PK PRIMARY KEY (COMPANY_NO)
);

CREATE TABLE COMM_EVENTS (
    EVENT_NO            NUMBER(4),
    EVENT_TITLE         VARCHAR2(255),
    EVENT_DESCRIPTION   VARCHAR2(255) NOT NULL,
    
    CONSTRAINT EVENTNO_PK PRIMARY KEY (EVENT_NO)
);

CREATE TABLE COMM_PRODUCT_STATUS (
    STATUS_NO   NUMBER(4),
    STATUS_NAME VARCHAR2(255) NOT NULL,
    
    CONSTRAINT PRODUCT_STATUSNO_PK PRIMARY KEY (STATUS_NO)
);

CREATE TABLE COMM_PRODUCTS (
    PRODUCT_NO              NUMBER(6),
    PRODUCT_NAME            VARCHAR2(255)   NOT NULL,
    CATEGORY_NO             NUMBER(4)       NOT NULL,
    COMPANY_NO              NUMBER(4)       NOT NULL,
    PRODUCT_PRICE           NUMBER(8)       NOT NULL,
    PRODUCT_DISCOUNT_PRICE  NUMBER(8)       NOT NULL,
    PRODUCT_DESCRIPTION     VARCHAR2(1000)  NOT NULL,
    STATUS_NO               NUMBER(4)       NOT NULL,
    PRODUCT_STOCK           NUMBER(5)       DEFAULT 100,
    PRODUCT_UPDATED_DATE    DATE            DEFAULT SYSDATE,
    PRODUCT_CREATED_DATE    DATE            DEFAULT SYSDATE,
    
    CONSTRAINT PRODUCTNO_PK PRIMARY KEY(PRODUCT_NO),
    CONSTRAINT PRODUCT_CATNO_FK FOREIGN KEY (CATEGORY_NO)
                                REFERENCES COMM_PRODUCT_CATEGORIES (CATEGORY_NO),
    CONSTRAINT PRODUCT_COMPANYNO_FK FOREIGN KEY (COMPANY_NO)
                              REFERENCES COMM_PRODUCT_COMPANIES (COMPANY_NO),
    CONSTRAINT PRODUCT_STATUSNO_FK FOREIGN KEY (STATUS_NO)
                            REFERENCES COMM_PRODUCT_STATUS (STATUS_NO)
);

CREATE TABLE COMM_PRODUCT_EVENTS (
    PRODUCT_NO  NUMBER(6) NOT NULL,
    EVENT_NO    NUMBER(4) NOT NULL,
    CONSTRAINT EVENTS_PRODUCTNO_FK FOREIGN KEY (PRODUCT_NO)
                                   REFERENCES COMM_PRODUCTS (PRODUCT_NO),
    CONSTRAINT EVENTS_EVENTNO_FK FOREIGN KEY (EVENT_NO)
                                   REFERENCES COMM_EVENTS (EVENT_NO)                              
);

create SEQUENCE products_seq start with 100000 NOCACHE;

select products_seq.nextval
from dual;


